apiVersion: v2
# renovate: image=ghcr.io/home-operations/tautulli
appVersion: 2.16.1
description: A Python based monitoring and tracking tool for Plex Media Server
name: tautulli
version: 12.2.1
kubeVersion: ">=1.32.0"
keywords:
  - tautulli
  - plex
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/tautulli
icon: https://github.com/Tautulli/Tautulli/blob/master/data/interfaces/default/images/logo.png?raw=true
sources:
  - https://github.com/Tautulli/Tautulli
  - https://github.com/home-operations/containers
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://k8s-home-lab.github.io/helm-charts/
    version: 4.5.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgrade common chart to 4.5.3
    - kind: changed
      description: Update minimum k8s version
    - kind: changed
      description: Fix home url
