apiVersion: v2
# renovate: image=ghcr.io/home-operations/readarr
appVersion: 0.4.18
description: A fork of Radarr to work with Books & AudioBooks
name: readarr
version: 7.2.0
kubeVersion: ">=1.32.0"
keywords:
  - readarr
  - torrent
  - usenet
  - AudioBooks
  - ebooks
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/readarr
icon: https://readarr.com/img/logo.png
sources:
  - https://github.com/Readarr/Readarr
  - https://github.com/home-operations/containers
maintainers:
  - name: mcmarkj
    email: mark@markmcw.uk
dependencies:
  - name: common
    repository: https://k8s-home-lab.github.io/helm-charts/
    version: 4.5.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgrade common chart to 4.5.3
    - kind: changed
      description: Update minimum k8s version
    - kind: changed
      description: Fix home url
