ghcr.io/onedr0p/readarr-develop
apiVersion: v2
appVersion: 0.3.3.2171
description: A fork of Radarr to work with Books & AudioBooks
name: readarr
version: 7.1.2
kubeVersion: ">=1.16.0-0"
keywords:
  - readarr
  - torrent
  - usenet
  - AudioBooks
  - ebooks
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/readarr
icon: https://readarr.com/img/logo.png
sources:
  - https://github.com/Readarr/Readarr
  - https://github.com/onedr0p/containers
maintainers:
  - name: mcmarkj
    email: mark@markmcw.uk
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update image to 0.3.3.2171
