apiVersion: v2
# renovate: image=ghcr.io/linuxserver/freshrss
appVersion: 1.21.0
description: FreshRSS is a self-hosted RSS feed aggregator
name: freshrss
version: 7.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - freshrss
  - rss
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/freshrss
icon: https://avatars.githubusercontent.com/u/9414285?s=200&v=4
sources:
  - https://github.com/FreshRSS/FreshRSS
  - https://hub.docker.com/r/linuxserver/freshrss
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Use ghcr.io image
