apiVersion: v2
# renovate: image=ghcr.io/paperless-ngx/paperless-ngx
appVersion: 1.17.4
description: Paperless - Index and archive all of your scanned paper documents
name: paperless
version: 10.1.1
kubeVersion: ">=1.16.0-0"
keywords:
  - paperless
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/paperless
icon: https://avatars.githubusercontent.com/u/47271576?s=200&v=4
sources:
  - https://github.com/paperless-ngx/paperless-ngx
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
  - name: postgresql
    version: 11.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 16.13.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Applied patch update of image redis to 16.13.2
