apiVersion: v2
# renovate: image=ghcr.io/0xerr0r/blocky
appVersion: v0.29.0
description: DNS proxy as ad-blocker for local network
name: blocky
version: 11.2.0
kubeVersion: ">=1.19.0-0"
keywords:
  - blocky
  - adblock
  - dns
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/blocky
icon: https://github.com/0xERR0R/blocky/raw/master/docs/blocky.svg?sanitize=true
sources:
  - https://github.com/0xERR0R/blocky
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://k8s-home-lab.github.io/helm-charts/
    version: 4.5.3
  - name: redis
    repository: oci://ghcr.io/cloudpirates-io/helm-charts
    version: 0.24.0
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Applied minor update of image ghcr.io/0xerr0r/blocky to v0.29.0
    - kind: changed
      description: Applied minor update of image ghcr.io/0xerr0r/blocky to v0.29.0
    - kind: changed
      description: Applied minor update of image ghcr.io/0xerr0r/blocky to v0.29.0
