apiVersion: v2
# renovate: image=prom/influxdb-exporter
appVersion: v0.11.4
description: An exporter for metrics in the InfluxDB format, transforms them and exposes them for consumption by Prometheus.
name: influxdb-exporter
version: 1.2.0
kubeVersion: ">=1.32.0"
keywords:
  - influxdb-exporter
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/influxdb-exporter
icon: https://influxdata.github.io/branding/img/downloads/influxdata-logo--symbol--pool.jpg
sources:
  - https://github.com/prometheus/influxdb_exporter
  - https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/influxdb-exporter
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://k8s-home-lab.github.io/helm-charts/
    version: 4.5.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgrade common chart to 4.5.3
    - kind: changed
      description: Update minimum k8s version
