apiVersion: v2
# renovate: image=ghcr.io/home-operations/qbittorrent
appVersion: 5.1.4
description: qBittorrent is a cross-platform free and open-source BitTorrent client
name: qbittorrent
version: 14.2.1
kubeVersion: ">=1.16.0-0"
keywords:
  - qbittorrent
  - torrrent
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/qbittorrent
icon: https://cloud.githubusercontent.com/assets/14862437/23586868/89ef2922-01c4-11e7-869c-52aafcece17f.png
sources:
  - https://github.com/qbittorrent/qBittorrent
  - https://github.com/home-operations/containers
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Added global values to fix library merging
