apiVersion: v2
# renovate: image=organizr/organizr
appVersion: latest
description: HTPC/Homelab Services Organizer
name: organizr
version: 8.1.0
kubeVersion: ">=1.32.0"
keywords:
  - organizr
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/organizr
icon: https://github.com/causefx/Organizr/blob/v2-master/plugins/images/organizr/logo.png?raw=true
sources:
  - https://github.com/causefx/Organizr
  - https://hub.docker.com/r/organizr/organizr
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://k8s-home-lab.github.io/helm-charts/
    version: 4.5.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgrade common chart to 4.5.3
    - kind: changed
      description: Update minimum k8s version
    - kind: changed
      description: Fix home url
