apiVersion: v2
# renovate: image=jesec/flood
appVersion: 4.11.0
description: Flood is a monitoring service for various torrent clients
name: flood
version: 7.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - flood
  - rtorrent
  - qbittorrent
  - transmission
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/flood
icon: https://raw.githubusercontent.com/jesec/flood/master/flood.svg
sources:
  - https://github.com/jesec/flood
  - https://hub.docker.com/r/jesec/flood
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Add chart
