apiVersion: v2
# renovate: image=jesec/flood
appVersion: 4.13.0
description: Flood is a monitoring service for various torrent clients
name: flood
version: 7.2.0
kubeVersion: ">=1.32.0"
keywords:
  - flood
  - rtorrent
  - qbittorrent
  - transmission
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/flood
icon: https://raw.githubusercontent.com/jesec/flood/master/flood.svg
sources:
  - https://github.com/jesec/flood
  - https://hub.docker.com/r/jesec/flood
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://k8s-home-lab.github.io/helm-charts/
    version: 4.5.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Applied minor update of image jesec/flood to 4.13.0
    - kind: changed
      description: Applied minor update of image jesec/flood to 4.13.0
    - kind: changed
      description: Applied minor update of image jesec/flood to 4.13.0
