apiVersion: v2
# renovate: image=ghcr.io/home-operations/lidarr
appVersion: 3.1.2
description: Looks and smells like Sonarr but made for music
name: lidarr
version: 15.2.0
kubeVersion: ">=1.16.0-0"
keywords:
  - lidarr
  - torrent
  - usenet
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/lidarr
icon: https://github.com/lidarr/Lidarr/blob/develop/Logo/512.png?raw=true
sources:
  - https://github.com/Lidarr/Lidarr
  - https://github.com/home-operations/containers
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Switch to ghcr.io/home-operations/lidarr 3.1.2
