apiVersion: v2
appVersion: 1.0.0
description: ${CHARTNAME} helm package
name: ${CHARTNAME}
version: 1.1.0
kubeVersion: ">=1.32.0"
keywords:
  - ${CHARTNAME}
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/${CHARTNAME}
icon: https://${CHARTNAME}.org/icon
sources:
  - https://github.com/${CHARTNAME}/${CHARTNAME}-docker
maintainers:
  - name: ${CHARTNAME}
    email: ${CHARTNAME}@${CHARTNAME}.com
dependencies:
  - name: common
    repository: https://k8s-home-lab.github.io/helm-charts/
    version: 4.5.3
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version
