apiVersion: v2
# renovate: image=ghcr.io/k8s-home-lab/wireguard
appVersion: v1.0.20210914
description: Fast, modern, secure VPN tunnel
name: wireguard
version: 1.5.2
kubeVersion: ">=1.16.0-0"
keywords:
  - vpn
  - privacy
  - security
  - wireguard
sources:
  - https://git.zx2c4.com/wireguard-tools
  - https://github.com/k8s-home-lab/container-images
icon: https://avatars.githubusercontent.com/u/13991055?s=200&v=4
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    version: 4.5.2
    repository: https://library-charts.k8s-at-home.com
annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: Fix app version
