apiVersion: v2
# renovate: image=ghcr.io/home-operations/plex
appVersion: 1.43.0.10467
description: Plex Media Server
name: plex
version: 7.3.0
kubeVersion: ">=1.30.0"
keywords:
  - plex
  - plex-media-server
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/plex
icon: https://www.plex.tv/wp-content/uploads/2018/01/pmp-icon-1.png
sources:
  - https://github.com/home-operations/containers/tree/main/apps/plex
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Applied minor update of image ghcr.io/home-operations/plex to 1.43.0.10467
