apiVersion: v2
# renovate: image=ghcr.io/flaresolverr/flaresolverr
appVersion: v3.4.6
description: FlareSolverr is a proxy server to bypass Cloudflare protection
name: flaresolverr
version: 6.0.4
kubeVersion: ">=1.16.0-0"
keywords:
  - flaresolverr
  - jackett
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/flaresolverr
icon: https://raw.githubusercontent.com/FlareSolverr/FlareSolverr/master/resources/flaresolverr_logo.svg
sources:
  - https://github.com/FlareSolverr/FlareSolverr
  - https://hub.docker.com/r/flaresolverr/flaresolverr
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Applied minor update of image ghcr.io/flaresolverr/flaresolverr to v3.4.6
