apiVersion: v2
# renovate: image=ghcr.io/haveagitgat/tdarr
appVersion: 2.58.02
description: Tdarr is a self hosted web-app for automating media library transcode/remux management and making sure your files are exactly how you need them to be in terms of codecs/streams/containers etc.
name: tdarr
version: 5.3.0
keywords:
  - transcoding
  - remux
  - media
  - video
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/tdarr
icon: https://s7.gifyu.com/images/GifCroppedTran.gif
sources:
  - https://www.github.com/HaveAGitGat/Tdarr
  - https://tdarr.io/docs/
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://k8s-home-lab.github.io/helm-charts/
    version: 4.5.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgrade common chart to 4.5.3
    - kind: changed
      description: Update minimum k8s version
    - kind: changed
      description: Fix home url
