apiVersion: v2
# renovate: image=ghcr.io/rogerfar/rdtclient
appVersion: 2.0.125
description: rdt-client helm package
name: rdt-client
version: 1.2.1
kubeVersion: ">=1.32.0"
keywords:
  - rdt-client
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/rdt-client
icon: https://github.com/rogerfar/rdt-client/blob/main/client/src/assets/logo.png?raw=true
sources:
  - https://github.com/rogerfar/rdt-client
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://k8s-home-lab.github.io/helm-charts/
    version: 4.5.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Applied patch update of image ghcr.io/rogerfar/rdtclient to 2.0.125
    - kind: changed
      description: Applied patch update of image ghcr.io/rogerfar/rdtclient to 2.0.125
