apiVersion: v2
# renovate: image=ghcr.io/onedr0p/bazarr
appVersion: v1.5.1
description: Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements
name: bazarr
version: 11.2.0
kubeVersion: ">=1.16.0-0"
keywords:
  - bazarr
  - radarr
  - sonarr
  - subtitles
  - usenet
  - torrent
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/bazarr
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr.png
sources:
  - https://github.com/morpheus65535/bazarr
  - https://github.com/onedr0p/containers
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Applied minor update of image ghcr.io/onedr0p/bazarr to v1.5.1
