apiVersion: v2
# renovate: image=ghcr.io/home-operations/bazarr
appVersion: 1.5.6
description: Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements
name: bazarr
version: 11.3.1
kubeVersion: ">=1.32.0"
keywords:
  - bazarr
  - radarr
  - sonarr
  - subtitles
  - usenet
  - torrent
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/bazarr
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr.png
sources:
  - https://github.com/morpheus65535/bazarr
  - https://github.com/home-operations/containers
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://k8s-home-lab.github.io/helm-charts/
    version: 4.5.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Applied patch update of image ghcr.io/home-operations/bazarr to 1.5.6
    - kind: changed
      description: Applied patch update of image ghcr.io/home-operations/bazarr to 1.5.6
