apiVersion: v2
# renovate: image=blakeblackshear/frigate
appVersion: 0.11.1
description: NVR With Realtime Object Detection for IP Cameras
name: frigate
version: 9.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - frigate
  - nvr
  - tensorflow
  - coral
  - ml
  - machine-learning
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/frigate
icon: https://github.com/blakeblackshear/frigate/blob/master/docs/static/img/frigate.png
sources:
  - https://github.com/blakeblackshear/frigate
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Add chart
