apiVersion: v2
# renovate: image=blakeblackshear/frigate
appVersion: 0.11.1
description: NVR With Realtime Object Detection for IP Cameras
name: frigate
version: 9.1.0
kubeVersion: ">=1.32.0"
keywords:
  - frigate
  - nvr
  - tensorflow
  - coral
  - ml
  - machine-learning
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/frigate
icon: https://github.com/blakeblackshear/frigate/blob/master/docs/static/img/frigate.png
sources:
  - https://github.com/blakeblackshear/frigate
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://k8s-home-lab.github.io/helm-charts/
    version: 4.5.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgrade common chart to 4.5.3
    - kind: changed
      description: Update minimum k8s version
    - kind: changed
      description: Fix home url
