apiVersion: v2
# renovate: image=ghcr.io/linuxserver/syslog-ng
appVersion: 4.10.2
description: syslog-ng allows you to flexibly collect, parse, classify, rewrite and correlate logs.
name: syslog-ng
version: 3.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - syslog-ng
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/syslog-ng
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/syslog-ng-logo.png
sources:
  - https://hub.docker.com/r/linuxserver/syslog-ng
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Applied major update of image ghcr.io/linuxserver/syslog-ng to 4.10.2
