apiVersion: v2
# renovate: image=ghcr.io/linuxserver/syslog-ng
appVersion: 4.10.2
description: syslog-ng allows you to flexibly collect, parse, classify, rewrite and correlate logs.
name: syslog-ng
version: 3.1.0
kubeVersion: ">=1.32.0"
keywords:
  - syslog-ng
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/syslog-ng
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/syslog-ng-logo.png
sources:
  - https://hub.docker.com/r/linuxserver/syslog-ng
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://k8s-home-lab.github.io/helm-charts/
    version: 4.5.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgrade common chart to 4.5.3
    - kind: changed
      description: Update minimum k8s version
    - kind: changed
      description: Fix home url
