apiVersion: v2
# renovate: image=linuxserver/beets
appVersion: 1.6.0
description: beets helm package
name: beets
version: 2.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - beets
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/beets
icon: https://pbs.twimg.com/profile_images/934307246/logo-square_400x400.png
sources:
  - https://github.com/beetbox/beets
  - https://github.com/linuxserver/docker-beets
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Add chart
