apiVersion: v2
# renovate: image=ghcr.io/home-operations/beets
appVersion: 2.3.1
description: beets helm package
name: beets
version: 3.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - beets
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/beets
icon: https://pbs.twimg.com/profile_images/934307246/logo-square_400x400.png
sources:
  - https://github.com/beetbox/beets
  - https://github.com/home-operations/containers
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Switch to ghcr.io/home-operations/beets 3.2.1
