name: "Charts: Release"

concurrency: helm-release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "charts/stable/**"
      - "charts/incubator/**"

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0

      - name: Install Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.13.1
        with:
          setup-tools: |
            helmv3
            yq

      - name: Install helm-docs
        run: |
          wget -O /tmp/helm-docs.deb https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.deb
          sudo dpkg -i /tmp/helm-docs.deb

      - name: Collect changes
        id: collect-changes
        uses: ./.github/actions/collect-changes

      - name: Generate README for changed charts
        if: |
          steps.collect-changes.outputs.changesDetected == 'true'
        run: |
          CHARTS=(${{ steps.collect-changes.outputs.addedOrModifiedCharts }})
          for i in "${CHARTS[@]}"
          do
              IFS='/' read -r -a chart_parts <<< "$i"
              if [ -f "charts/${chart_parts[0]}"/"${chart_parts[1]}/Chart.yaml" ]; then
                ./.github/scripts/gen-helm-docs.sh "${chart_parts[0]}" "${chart_parts[1]}"
              fi
          done

      - name: Create commit
        id: create-commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          file_pattern: charts/**/*
          commit_message: "chore: Auto-update chart README [skip ci]"
          commit_user_name: helm[bot]
          commit_user_email: helm[bot]@users.noreply.github.com
          commit_author: helm[bot] <helm[bot]@users.noreply.github.com>

      - name: Save commit hash
        id: save-commit-hash
        run: |
          if [ "${{ steps.create-commit.outputs.changes_detected || 'unknown' }}" == "true" ]; then
            echo '::set-output name=commit_hash::${{ steps.create-commit.outputs.commit_hash }}'
          else
            echo "::set-output name=commit_hash::${GITHUB_SHA}"
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: ${{ steps.save-commit-hash.outputs.commit_hash }}
          fetch-depth: 0
          persist-credentials: falsemit-hash.outputs.commit_hash }}

      - name: Configure Git
        run: |
          git config user.name "helm[bot]"
          git config user.email "helm[bot]@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1
        with:
          charts_dir: charts/*
        env:
          CR_TOKEN: "${{ steps.generate-token.outputs.token }}"
          CR_SKIP_EXISTING: "true"

  generate-summary:
    name: Auto-generate charts summary
    runs-on: ubuntu-24.04
    needs:
      - release
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0

      - name: Install yq
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: v4.50.1

      - name: Run script
        run: |
          ./scripts/gen-chart-summary.sh

      - name: Create Commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          push_options: --force
          commit_message: Auto-generate chart summary [no ci]
          commit_user_name: helm[bot]
          commit_user_email: helm[bot]@users.noreply.github.com
          commit_author: helm[bot] <helm[bot]@users.noreply.github.com>
          file_pattern: charts/README.md
