{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "gitea.harcodedValues" -}}
envFrom:
  - configMapRef:
      name: {{ include "common.names.fullname" . }}-config
  - secretRef:
      name: {{ include "common.names.fullname" . }}-secret
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "gitea.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}