apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-secret
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.postgresql.enabled }}
  GITEA__database__PASSWD: {{ .Values.postgresql.auth.password | b64enc }}
  {{ end }}
  {{ if .Values.mariadb.enabled }}
  GITEA__database__PASSWD: {{ .Values.mariadb.auth.password | b64enc }}
  {{ end }}