apiVersion: v2
# renovate: image=ghcr.io/home-operations/prowlarr
appVersion: 2.3.2
description: Indexer manager/proxy built on the popular arr net base stack to integrate with your various PVR apps.
name: prowlarr
version: 5.2.0
kubeVersion: ">=1.16.0-0"
keywords:
  - prowlarr
  - torrent
  - usenet
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/prowlarr
icon: https://raw.githubusercontent.com/Prowlarr/Prowlarr/develop/Logo/400.png
sources:
  - https://github.com/Prowlarr/Prowlarr
  - https://github.com/home-operations/containers
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Switch to ghcr.io/home-operations/prowlarr 2.3.2
